version : "3.2"
services:

  ela-mainchain-normal:
    container_name: ela-mainchain-normal
    image: ela-mainchain-normal
    build:
      context: ela-mainchain/mainchain-normal
    ports:
      - 20333-20338:20333-20338
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:20334/api/v1/node/connectioncount"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - blockchain
    tty: true

  ela-mainchain-crc-1:
    container_name: ela-mainchain-crc-1
    image: ela-mainchain-crc-1
    depends_on:
      - ela-mainchain-normal
    build:
      context: ela-mainchain/mainchain-crc-1
    ports:
      - 21333-21339:20333-20339
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:21334/api/v1/node/connectioncount"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - blockchain
    tty: true
    
  ela-mainchain-crc-2:
    container_name: ela-mainchain-crc-2
    image: ela-mainchain-crc-2
    depends_on:
      - ela-mainchain-normal
    build:
      context: ela-mainchain/mainchain-crc-2
    ports:
      - 22333-22339:20333-20339
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:22334/api/v1/node/connectioncount"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - blockchain
    tty: true

  ela-sidechain-did:
    container_name: ela-sidechain-did
    image: ela-sidechain-did
    build:
      context: ela-sidechain/did
    ports:
      - 20604-20608:20604-20608
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:20604/api/v1/node/connectioncount"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - blockchain
    tty: true

  ela-arbitrator-crc-1:
    container_name: ela-arbitrator-crc-1
    image: ela-arbitrator-crc-1
    depends_on:
      - ela-sidechain-did
    build:
      context: ela-arbitrator/arbitrator-crc-1
    ports:
      - 10536:10536
      - 10538:10538
    networks:
      - blockchain
    tty: true

  ela-arbitrator-crc-2:
    container_name: ela-arbitrator-crc-2
    image: ela-arbitrator-crc-2
    depends_on:
      - ela-sidechain-did
    build:
      context: ela-arbitrator/arbitrator-crc-2
    ports:
      - 11536:10536
      - 11538:10538
    networks:
      - blockchain
    tty: true

  ela-wallet-service:
    container_name: ela-wallet-service
    image: ela-wallet-service
    depends_on:
      - ela-mainchain-normal
    build:
      context: restful-services/wallet-service
    ports:
      - 8091:8091
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8091/api/1/currHeight"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - blockchain
    tty: true 

  ela-did-service:
    container_name: ela-did-service
    image: ela-did-service
    depends_on:
      - ela-sidechain-did
    build:
      context: restful-services/did-service
    ports:
      - 8092:8092
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8092/api/1/currHeight"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - blockchain
    tty: true  

networks:
  blockchain:
  hive:

