version : "3.2"
services:

  ela-mainchain:
    container_name: ela-mainchain
    image: elastos-mainchain
    build:
      context: .
      dockerfile: Dockerfile-ela
    ports:
      - 20334:20334
    tty: true


