version : "3.2"
services:

  ela-mainchain:
    container_name: ela-mainchain
    image: ela-mainchain
    build:
      context: .
      dockerfile: Dockerfile-ela
    ports:
      - 20333-20338:20333-20338
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:20334/api/v1/node/connectioncount"]
      interval: 5s
      timeout: 5s
      retries: 10
    tty: true

  ela-sidechain-did:
    container_name: ela-sidechain-did
    image: ela-sidechain-did
    depends_on:
      - ela-mainchain
    build:
      context: .
      dockerfile: Dockerfile-did
    ports:
      - 20604-20608:20604-20608
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:20604/api/v1/node/connectioncount"]
      interval: 5s
      timeout: 5s
      retries: 10
    tty: true

  ela-arbiter-1:
    container_name: ela-arbiter-1
    image: ela-arbiter
    depends_on:
      - ela-mainchain
      - ela-sidechain-did
    restart: on-failure
    build:
      context: .
      dockerfile: Dockerfile-ela-arbiter-1
    ports:
      - 10336:10336
      - 10338:10338
    tty: true

  ela-arbiter-2:
    container_name: ela-arbiter-2
    image: ela-arbiter
    depends_on:
      - ela-mainchain
      - ela-sidechain-did
    restart: on-failure
    build:
      context: .
      dockerfile: Dockerfile-ela-arbiter-2
    ports:
      - 11336:11336
      - 11338:11338
    tty: true

  mysql-db-simple:
    container_name: mysql-db-simple
    image: mysql:5.6
    environment:
      - MYSQL_ROOT_PASSWORD=12345678
      - MYSQL_DATABASE=ws
      - MYSQL_USER=elastos
      - MYSQL_PASSWORD=12345678
    ports: 
      - 3306:3307
    tty: true

  ela-wallet-service:
    container_name: ela-wallet-service
    image: ela-wallet-service
    depends_on:
      - mysql-db-simple
      - ela-mainchain
    build:
      context: .
      dockerfile: Dockerfile-wallet-service
    ports:
      - 8091:8091
    tty: true   
    
  ela-did-service:
    container_name: ela-did-service
    image: ela-did-service
    depends_on:
      - ela-sidechain-did
    build:
      context: .
      dockerfile: Dockerfile-did-service
    ports:
      - 8092:8092
    tty: true  


