apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert --volumes hostPath --verbose
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: privnet-arbitrator-origin-1
  name: privnet-arbitrator-origin-1
spec:
  ports:
  - name: "50514"
    port: 50514
    targetPort: 20534
  - name: "50515"
    port: 50515
    targetPort: 20535
  - name: "50516"
    port: 50516
    targetPort: 20536
  - name: "50517"
    port: 50517
    targetPort: 20537
  - name: "50518"
    port: 50518
    targetPort: 20538
  selector:
    io.kompose.service: privnet-arbitrator-origin-1
  type: NodePort
status:
  loadBalancer: {}
