apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert --volumes hostPath --verbose
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: privnet-wallet-service-tokensidechain
  name: privnet-wallet-service-tokensidechain
spec:
  ports:
  - name: "8093"
    port: 8093
    targetPort: 8080
  selector:
    io.kompose.service: privnet-wallet-service-tokensidechain
  type: NodePort
status:
  loadBalancer: {}
