apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert --volumes hostPath --verbose
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: privnet-wallet-service
  name: privnet-wallet-service
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      io.kompose.service: privnet-wallet-service
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: privnet-wallet-service
    spec:
      containers:
      - image: cyberrepublic/elastos-wallet-service:privnet-v0.6
        livenessProbe:
          exec:
            command:
            - curl
            - -f
            - http://localhost:8091/api/1/currHeight
          failureThreshold: 5
          periodSeconds: 30
          timeoutSeconds: 120
        name: privnet-wallet-service
        ports:
        - containerPort: 8080
        resources: {}
        tty: true
        volumeMounts:
        - mountPath: /home/elauser/application.properties
          name: privnet-wallet-service-hostpath0
      restartPolicy: Always
      volumes:
      - hostPath:
          path: /home/kpachhai/dev/src/github.com/tuum-tech/elastos-privnet/blockchain/restful-services/wallet/application-mainchain-did.properties
        name: privnet-wallet-service-hostpath0
status: {}
