apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert --volumes hostPath --verbose
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: privnet-sidechain-eth-node
  name: privnet-sidechain-eth-node
spec:
  ports:
  - name: "60111"
    port: 60111
    targetPort: 20635
  - name: "60112"
    port: 60112
    targetPort: 20636
  - name: "60113"
    port: 60113
    targetPort: 20638
  selector:
    io.kompose.service: privnet-sidechain-eth-node
  type: NodePort
status:
  loadBalancer: {}
