apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert --volumes hostPath --verbose
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: privnet-wallet-service
  name: privnet-wallet-service
spec:
  ports:
  - name: "8091"
    port: 8091
    targetPort: 8080
  selector:
    io.kompose.service: privnet-wallet-service
  type: NodePort
status:
  loadBalancer: {}
