apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert --volumes hostPath --verbose
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: privnet-api-misc-mainchain
  name: privnet-api-misc-mainchain
spec:
  ports:
  - name: "9091"
    port: 9091
    targetPort: 8080
  selector:
    io.kompose.service: privnet-api-misc-mainchain
  type: NodePort
status:
  loadBalancer: {}
