apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert --volumes hostPath --verbose
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: privnet-mainchain-node
  name: privnet-mainchain-node
spec:
  ports:
  - name: "10011"
    port: 10011
    targetPort: 20333
  - name: "10012"
    port: 10012
    targetPort: 20334
  - name: "10013"
    port: 10013
    targetPort: 20335
  - name: "10014"
    port: 10014
    targetPort: 20336
  - name: "10015"
    port: 10015
    targetPort: 20337
  - name: "10016"
    port: 10016
    targetPort: 20338
  - name: "10017"
    port: 10017
    targetPort: 20339
  selector:
    io.kompose.service: privnet-mainchain-node
  type: NodePort
status:
  loadBalancer: {}
