apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert --volumes hostPath --verbose
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: privnet-sidechain-eth-oracle-node
  name: privnet-sidechain-eth-oracle-node
spec:
  ports:
  - name: "60114"
    port: 60114
    targetPort: 20632
  selector:
    io.kompose.service: privnet-sidechain-eth-oracle-node
  type: NodePort
status:
  loadBalancer: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert --volumes hostPath --verbose
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: privnet-sidechain-eth-oracle-node
  name: privnet-sidechain-eth-oracle-node
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      io.kompose.service: privnet-sidechain-eth-oracle-node
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: privnet-sidechain-eth-oracle-node
    spec:
      containers:
      - image: cyberrepublic/elastos-sidechain-eth-oracle:privnet-v0.6
        name: privnet-sidechain-eth-oracle-node
        ports:
        - containerPort: 20632
        resources: {}
        tty: true
      restartPolicy: Always
status: {}
