version : "3"
services:

  privnet-mainchain-node:
    container_name: privnet-mainchain-node
    image: cyberrepublic/elastos-mainchain-node:privnet-v0.4
    user: "${UID}:${GID}"
    volumes:
      - ~/.volumes/elastos-privnet/mainchain-node:/ela/elastos
      - ${PWD}/ela-mainchain/node_normal/mainchain-node/config.json:/ela/config.json
      - ${PWD}/ela-mainchain/node_normal/mainchain-node/keystore.dat:/ela/keystore.dat
    ports:
      - 10011-10017:20333-20339
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:10012/api/v1/block/height"]
      interval: 30s
      timeout: 120s
      retries: 5
    networks:
      - blockchain
    tty: true

  privnet-mainchain-crc-1:
    container_name: privnet-mainchain-crc-1
    image: cyberrepublic/elastos-mainchain-node:privnet-v0.4
    user: "${UID}:${GID}"
    volumes:
      - ~/.volumes/elastos-privnet/mainchain-crc-1:/ela/elastos
      - ${PWD}/ela-mainchain/node_crc/mainchain-crc-1/config.json:/ela/config.json
      - ${PWD}/ela-mainchain/node_crc/mainchain-crc-1/keystore.dat:/ela/keystore.dat
    ports:
      - 10111-10117:20333-20339
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:10112/api/v1/block/height"]
      interval: 30s
      timeout: 120s
      retries: 5
    networks:
      - blockchain
    tty: true

  privnet-mainchain-crc-2:
    container_name: privnet-mainchain-crc-2
    image: cyberrepublic/elastos-mainchain-node:privnet-v0.4
    user: "${UID}:${GID}"
    volumes:
      - ~/.volumes/elastos-privnet/mainchain-crc-2:/ela/elastos
      - ${PWD}/ela-mainchain/node_crc/mainchain-crc-2/config.json:/ela/config.json
      - ${PWD}/ela-mainchain/node_crc/mainchain-crc-2/keystore.dat:/ela/keystore.dat
    ports:
      - 10211-10217:20333-20339
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:10212/api/v1/block/height"]
      interval: 30s
      timeout: 120s
      retries: 5
    networks:
      - blockchain
    tty: true

  privnet-mainchain-dpos-1:
    container_name: privnet-mainchain-dpos-1
    image: cyberrepublic/elastos-mainchain-node:privnet-v0.4
    user: "${UID}:${GID}"
    volumes:
      - ~/.volumes/elastos-privnet/mainchain-dpos-1:/ela/elastos
      - ${PWD}/ela-mainchain/node_dpos/mainchain-dpos-1/config.json:/ela/config.json
      - ${PWD}/ela-mainchain/node_dpos/mainchain-dpos-1/keystore.dat:/ela/keystore.dat
    ports:
      - 10511-10517:20333-20339
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:10512/api/v1/block/height"]
      interval: 30s
      timeout: 120s
      retries: 5
    networks:
      - blockchain
    tty: true

  privnet-mainchain-dpos-2:
    container_name: privnet-mainchain-dpos-2
    image: cyberrepublic/elastos-mainchain-node:privnet-v0.4
    user: "${UID}:${GID}"
    volumes:
      - ~/.volumes/elastos-privnet/mainchain-dpos-2:/ela/elastos
      - ${PWD}/ela-mainchain/node_dpos/mainchain-dpos-2/config.json:/ela/config.json
      - ${PWD}/ela-mainchain/node_dpos/mainchain-dpos-2/keystore.dat:/ela/keystore.dat
    ports:
      - 10611-10617:20333-20339
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:10612/api/v1/block/height"]
      interval: 30s
      timeout: 120s
      retries: 5
    networks:
      - blockchain
    tty: true

  privnet-arbitrator-crc-1:
    container_name: privnet-arbitrator-crc-1
    image: cyberrepublic/elastos-arbitrator-node:privnet-v0.4
    user: "${UID}:${GID}"
    depends_on:
      - privnet-mainchain-crc-1
    volumes:
      - ~/.volumes/elastos-privnet/arbitrator-crc-1:/arbiter/elastos_arbiter
      - ${PWD}/ela-arbitrator/node_crc/arbitrator-crc-1/config.json:/arbiter/config.json
      - ${PWD}/ela-arbitrator/node_crc/arbitrator-crc-1/keystore.dat:/arbiter/keystore.dat
    ports:
      - 50114-50118:20534-20538
    networks:
      - blockchain
    tty: true

  privnet-arbitrator-crc-2:
    container_name: privnet-arbitrator-crc-2
    image: cyberrepublic/elastos-arbitrator-node:privnet-v0.4
    user: "${UID}:${GID}"
    depends_on:
      - privnet-mainchain-crc-2
    volumes:
      - ~/.volumes/elastos-privnet/arbitrator-crc-2:/arbiter/elastos_arbiter
      - ${PWD}/ela-arbitrator/node_crc/arbitrator-crc-2/config.json:/arbiter/config.json
      - ${PWD}/ela-arbitrator/node_crc/arbitrator-crc-2/keystore.dat:/arbiter/keystore.dat
    ports:
      - 50214-50218:20534-20538
    networks:
      - blockchain
    tty: true

  privnet-arbitrator-origin-1:
    container_name: privnet-arbitrator-origin-1
    image: cyberrepublic/elastos-arbitrator-node:privnet-v0.4
    user: "${UID}:${GID}"
    depends_on:
      - privnet-mainchain-dpos-1
    volumes:
      - ~/.volumes/elastos-privnet/arbitrator-origin-1:/arbiter/elastos_arbiter
      - ${PWD}/ela-arbitrator/node_origin/arbitrator-origin-1/config.json:/arbiter/config.json
      - ${PWD}/ela-arbitrator/node_origin/arbitrator-origin-1/keystore.dat:/arbiter/keystore.dat
    ports:
      - 50514-50518:20534-20538
    networks:
      - blockchain
    tty: true

  privnet-arbitrator-origin-2:
    container_name: privnet-arbitrator-origin-2
    image: cyberrepublic/elastos-arbitrator-node:privnet-v0.4
    user: "${UID}:${GID}"
    depends_on:
      - privnet-mainchain-dpos-2
    volumes:
      - ~/.volumes/elastos-privnet/arbitrator-origin-2:/arbiter/elastos_arbiter
      - ${PWD}/ela-arbitrator/node_origin/arbitrator-origin-2/config.json:/arbiter/config.json
      - ${PWD}/ela-arbitrator/node_origin/arbitrator-origin-2/keystore.dat:/arbiter/keystore.dat
    ports:
      - 50614-50618:20534-20538
    networks:
      - blockchain
    tty: true

  privnet-sidechain-did-node:
    container_name: privnet-sidechain-did-node
    image: cyberrepublic/elastos-sidechain-did-node:privnet-v0.4
    user: "${UID}:${GID}"
    volumes:
      - ~/.volumes/elastos-privnet/did-node:/did/elastos_did
      - ${PWD}/ela-sidechain/did/did-node/config.json:/did/config.json
    ports:
      - 30111-30115:20604-20608
    networks:
      - blockchain
    tty: true 

  privnet-sidechain-token-node:
    container_name: privnet-sidechain-token-node
    image: cyberrepublic/elastos-sidechain-token-node:privnet-v0.4
    user: "${UID}:${GID}"
    volumes:
      - ~/.volumes/elastos-privnet/token-node:/token/elastos_token
      - ${PWD}/ela-sidechain/token/token-node/config.json:/token/config.json
    ports:
      - 40111-40115:20614-20618
    networks:
      - blockchain
    tty: true 

  privnet-sidechain-eth-node:
    container_name: privnet-sidechain-eth-node
    image: cyberrepublic/elastos-sidechain-eth-node:privnet-v0.4
    user: "${UID}:${GID}"
    volumes:
      - ~/.volumes/elastos-privnet/eth-node:/eth/elastos_eth
      - ${PWD}/ela-sidechain/eth/eth-node/eth-accounts-pass.txt:/eth/eth-accounts-pass.txt
    ports:
      - 60011:8545
      - 60012:30303
    networks:
      - blockchain
    tty: true 

  privnet-sidechain-eth-oracle-node:
    container_name: privnet-sidechain-eth-oracle-node
    image: cyberrepublic/elastos-sidechain-eth-oracle:privnet-v0.4
    user: "${UID}:${GID}"
    depends_on:
      - privnet-sidechain-eth-node
    ports:
      - 60113:16666
    networks:
      - blockchain
    tty: true 

  privnet-wallet-service:
    container_name: privnet-wallet-service
    image: cyberrepublic/elastos-wallet-service:privnet-v0.4
    user: "${UID}:${GID}"
    depends_on:
      - privnet-mainchain-node
    ports:
      - 8091:8080
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8091/api/1/currHeight"]
      interval: 30s
      timeout: 120s
      retries: 5
    networks:
      - blockchain
    tty: true 

  privnet-sidechain-service:
    container_name: privnet-sidechain-service
    image: cyberrepublic/elastos-sidechain-service:privnet-v0.4
    user: "${UID}:${GID}"
    depends_on:
      - privnet-sidechain-did-node
    ports:
      - 8092:8080
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8092/api/1/currHeight"]
      interval: 30s
      timeout: 120s
      retries: 5
    networks:
      - blockchain
    tty: true 

  privnet-api-misc-mainchain:
    container_name: privnet-api-misc-mainchain
    image: cyberrepublic/elastos-api-misc-service:privnet-v0.4
    user: "${UID}:${GID}"
    volumes:
      - ${PWD}/restful-services/api-misc/mainchain/config.json:/home/elauser/config.json
      - ${PWD}/restful-services/api-misc/mainchain/deploy.sh:/home/elauser/deploy.sh
    depends_on:
      - privnet-mysql
      - privnet-mainchain-node
    ports:
      - 9091:8080
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9091/api/1/history/checking/sync"]
      interval: 30s
      timeout: 120s
      retries: 5
    networks:
      - blockchain
    tty: true

  privnet-api-misc-sidechain-did:
    container_name: privnet-api-misc-sidechain-did
    image: cyberrepublic/elastos-api-misc-service:privnet-v0.4
    user: "${UID}:${GID}"
    volumes:
      - ${PWD}/restful-services/api-misc/sidechain/did/config.json:/home/elauser/config.json
      - ${PWD}/restful-services/api-misc/sidechain/did/deploy.sh:/home/elauser/deploy.sh
    depends_on:
      - privnet-mysql
      - privnet-sidechain-did-node
    ports:
      - 9092:8080
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9092/api/1/history/checking/sync"]
      interval: 30s
      timeout: 120s
      retries: 5
    networks:
      - blockchain
    tty: true

  privnet-mysql:
    container_name: privnet-mysql
    image: mysql:5.7
    user: "${UID}:${GID}"
    volumes:
      - ~/.volumes/elastos-privnet/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=12345678
      - MYSQL_DATABASE=ws
      - MYSQL_USER=elastos
      - MYSQL_PASSWORD=12345678
    ports:
      - 3307:3306
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-p12345678"]
      interval: 30s
      timeout: 120s
      retries: 5
    networks:
      - blockchain
    tty: true

networks:
  blockchain:
