version : "3.2"
services:

  ela-mainchain-normal-1:
    container_name: ela-mainchain-normal-1
    image: ela-mainchain-normal-1
    build:
      context: ela-mainchain/node_normal/mainchain-normal-1
    ports:
      - 10011-10016:10011-10016
    networks:
      - blockchain
    tty: true

  ela-mainchain-crc-1:
    container_name: ela-mainchain-crc-1
    image: ela-mainchain-crc-1
    build:
      context: ela-mainchain/node_crc/mainchain-crc-1
    ports:
      - 10111-10116:10111-10116
    networks:
      - blockchain
    tty: true

  ela-mainchain-crc-2:
    container_name: ela-mainchain-crc-2
    image: ela-mainchain-crc-2
    build:
      context: ela-mainchain/node_crc/mainchain-crc-2
    ports:
      - 10211-10216:10211-10216
    networks:
      - blockchain
    tty: true

  ela-mainchain-crc-3:
    container_name: ela-mainchain-crc-3
    image: ela-mainchain-crc-3
    build:
      context: ela-mainchain/node_crc/mainchain-crc-3
    ports:
      - 10311-10316:10311-10316
    networks:
      - blockchain
    tty: true

  ela-mainchain-crc-4:
    container_name: ela-mainchain-crc-4
    image: ela-mainchain-crc-4
    build:
      context: ela-mainchain/node_crc/mainchain-crc-4
    ports:
      - 10411-10416:10411-10416
    networks:
      - blockchain
    tty: true

  ela-mainchain-dpos-1:
    container_name: ela-mainchain-dpos-1
    image: ela-mainchain-dpos-1
    build:
      context: ela-mainchain/node_dpos/mainchain-dpos-1
    ports:
      - 10511-10516:10511-10516
    networks:
      - blockchain
    tty: true

  ela-mainchain-dpos-2:
    container_name: ela-mainchain-dpos-2
    image: ela-mainchain-dpos-2
    build:
      context: ela-mainchain/node_dpos/mainchain-dpos-2
    ports:
      - 10611-10616:10611-10616
    networks:
      - blockchain
    tty: true

  ela-arbitrator-origin-1:
    container_name: ela-arbitrator-origin-1
    image: ela-arbitrator-origin-1
    depends_on:
      - ela-mainchain-dpos-1
      - ela-sidechain-did-1
      - ela-sidechain-token-1
    build:
      context: ela-arbitrator/node_origin/arbitrator-origin-1
    ports:
      - 10024-10025:10024-10025
    networks:
      - blockchain
    tty: true

  ela-arbitrator-origin-2:
    container_name: ela-arbitrator-origin-2
    image: ela-arbitrator-origin-2
    depends_on:
      - ela-mainchain-dpos-2
      - ela-sidechain-did-2
      - ela-sidechain-token-2
    build:
      context: ela-arbitrator/node_origin/arbitrator-origin-2
    ports:
      - 10124-10125:10124-10125
    networks:
      - blockchain
    tty: true

  ela-arbitrator-crc-1:
    container_name: ela-arbitrator-crc-1
    image: ela-arbitrator-crc-1
    depends_on:
      - ela-mainchain-crc-1
      - ela-sidechain-did-1
      - ela-sidechain-token-1
    build:
      context: ela-arbitrator/node_crc/arbitrator-crc-1
    ports:
      - 10524-10525:10524-10525
    networks:
      - blockchain
    tty: true

  ela-arbitrator-crc-2:
    container_name: ela-arbitrator-crc-2
    image: ela-arbitrator-crc-2
    depends_on:
      - ela-mainchain-crc-2
      - ela-sidechain-did-2
      - ela-sidechain-token-2
    build:
      context: ela-arbitrator/node_crc/arbitrator-crc-2
    ports:
      - 10624-10625:10624-10625
    networks:
      - blockchain
    tty: true

  ela-arbitrator-crc-3:
    container_name: ela-arbitrator-crc-3
    image: ela-arbitrator-crc-3
    depends_on:
      - ela-mainchain-crc-3
      - ela-sidechain-did-3
      - ela-sidechain-token-3
    build:
      context: ela-arbitrator/node_crc/arbitrator-crc-3
    ports:
      - 10724-10725:10724-10725
    networks:
      - blockchain
    tty: true

  ela-arbitrator-crc-4:
    container_name: ela-arbitrator-crc-4
    image: ela-arbitrator-crc-4
    depends_on:
      - ela-mainchain-crc-4
      - ela-sidechain-did-4
      - ela-sidechain-token-4
    build:
      context: ela-arbitrator/node_crc/arbitrator-crc-4
    ports:
      - 10824-10825:10824-10825
    networks:
      - blockchain
    tty: true

  ela-sidechain-did-1:
    container_name: ela-sidechain-did-1
    image: ela-sidechain-did-1
    depends_on:
      - ela-mainchain-dpos-1
      - ela-mainchain-crc-1
    build:
      context: ela-sidechain/did/did-1
    ports:
      - 10031-10035:10031-10035
    networks:
      - blockchain
    tty: true 

  ela-sidechain-did-2:
    container_name: ela-sidechain-did-2
    image: ela-sidechain-did-2
    depends_on:
      - ela-mainchain-dpos-2
      - ela-mainchain-crc-2
    build:
      context: ela-sidechain/did/did-2
    ports:
      - 10131-10135:10131-10135
    networks:
      - blockchain
    tty: true 

  ela-sidechain-did-3:
    container_name: ela-sidechain-did-3
    image: ela-sidechain-did-3
    depends_on:
      - ela-mainchain-crc-3
    build:
      context: ela-sidechain/did/did-3
    ports:
      - 10231-10235:10231-10235
    networks:
      - blockchain
    tty: true 

  ela-sidechain-did-4:
    container_name: ela-sidechain-did-4
    image: ela-sidechain-did-4
    depends_on:
      - ela-mainchain-crc-4
    build:
      context: ela-sidechain/did/did-4
    ports:
      - 10331-10335:10331-10335
    networks:
      - blockchain
    tty: true 

  ela-sidechain-token-1:
    container_name: ela-sidechain-token-1
    image: ela-sidechain-token-1
    depends_on:
      - ela-mainchain-dpos-1
      - ela-mainchain-crc-1
    build:
      context: ela-sidechain/token/token-1
    ports:
      - 10041-10045:10041-10045
    networks:
      - blockchain
    tty: true 

  ela-sidechain-token-2:
    container_name: ela-sidechain-token-2
    image: ela-sidechain-token-2
    depends_on:
      - ela-mainchain-dpos-2
      - ela-mainchain-crc-2
    build:
      context: ela-sidechain/token/token-2
    ports:
      - 10141-10145:10141-10145
    networks:
      - blockchain
    tty: true 

  ela-sidechain-token-3:
    container_name: ela-sidechain-token-3
    image: ela-sidechain-token-3
    depends_on:
      - ela-mainchain-crc-3
    build:
      context: ela-sidechain/token/token-3
    ports:
      - 10241-10245:10241-10245
    networks:
      - blockchain
    tty: true 

  ela-sidechain-token-4:
    container_name: ela-sidechain-token-4
    image: ela-sidechain-token-4
    depends_on:
      - ela-mainchain-crc-4
    build:
      context: ela-sidechain/token/token-4
    ports:
      - 10341-10345:10341-10345
    networks:
      - blockchain
    tty: true 

  ela-wallet-service:
    container_name: ela-wallet-service
    image: ela-wallet-service
    depends_on:
      - ela-mainchain-normal-1
    build:
      context: restful-services/wallet-service
    ports:
      - 8091:8091
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8091/api/1/currHeight"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - blockchain
    tty: true 

  ela-did-service:
    container_name: ela-did-service
    image: ela-did-service
    depends_on:
      - ela-sidechain-did-1
    build:
      context: restful-services/did-service
    ports:
      - 8092:8092
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8092/api/1/currHeight"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - blockchain
    tty: true 

  ela-api-misc-mainchain:
    container_name: ela-api-misc-mainchain
    image: ela-api-misc-mainchain
    depends_on:
      - ela-mysql
      - ela-mainchain-normal-1
    build:
      context: restful-services/api-misc
      dockerfile: mainchain/Dockerfile
    ports:
      - 8093:8093
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8093/api/1/ping"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - blockchain
    tty: true

  ela-api-misc-sidechain-did:
    container_name: ela-api-misc-sidechain-did
    image: ela-api-misc-sidechain-did
    depends_on:
      - ela-mysql
      - ela-sidechain-did-1
    build:
      context: restful-services/api-misc
      dockerfile: sidechain/did/Dockerfile
    ports:
      - 8094:8093
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8094/api/1/ping"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - blockchain
    tty: true

  ela-mysql:
    container_name: ela-mysql
    image: mysql:5.6
    environment:
      - MYSQL_ROOT_PASSWORD=12345678
      - MYSQL_DATABASE=ws
      - MYSQL_USER=elastos
      - MYSQL_PASSWORD=12345678
    ports:
      - 3307:3306
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 20s
      retries: 10
    networks:
      - blockchain
    tty: true

networks:
  blockchain:
