version : "3"
services:

  ela-mainchain-normal-1:
    container_name: ela-mainchain-normal-1
    image: cyberrepublic/elastos-mainchain-node:v0.3.2
    volumes:
      - ~/.volumes/elastos-privnet/mainchain-normal-1:/ela/elastos
      - ${PWD}/ela-mainchain/node_normal/mainchain-normal-1/config.json:/ela/config.json
      - ${PWD}/ela-mainchain/node_normal/mainchain-normal-1/keystore.dat:/ela/keystore.dat
    ports:
      - 10011-10017:20333-20339
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:10012/api/v1/block/height"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - blockchain
    tty: true

  ela-mainchain-crc-1:
    container_name: ela-mainchain-crc-1
    image: cyberrepublic/elastos-mainchain-node:v0.3.2
    depends_on:
      - ela-mainchain-normal-1
    volumes:
      - ~/.volumes/elastos-privnet/mainchain-crc-1:/ela/elastos
      - ${PWD}/ela-mainchain/node_crc/mainchain-crc-1/config.json:/ela/config.json
      - ${PWD}/ela-mainchain/node_crc/mainchain-crc-1/keystore.dat:/ela/keystore.dat
    ports:
      - 10111-10117:20333-20339
    networks:
      - blockchain
    tty: true

  ela-mainchain-crc-2:
    container_name: ela-mainchain-crc-2
    image: cyberrepublic/elastos-mainchain-node:v0.3.2
    depends_on:
      - ela-mainchain-normal-1
    volumes:
      - ~/.volumes/elastos-privnet/mainchain-crc-2:/ela/elastos
      - ${PWD}/ela-mainchain/node_crc/mainchain-crc-2/config.json:/ela/config.json
      - ${PWD}/ela-mainchain/node_crc/mainchain-crc-2/keystore.dat:/ela/keystore.dat
    ports:
      - 10211-10217:20333-20339
    networks:
      - blockchain
    tty: true

  ela-mainchain-crc-3:
    container_name: ela-mainchain-crc-3
    image: cyberrepublic/elastos-mainchain-node:v0.3.2
    depends_on:
      - ela-mainchain-normal-1
    volumes:
      - ~/.volumes/elastos-privnet/mainchain-crc-3:/ela/elastos
      - ${PWD}/ela-mainchain/node_crc/mainchain-crc-3/config.json:/ela/config.json
      - ${PWD}/ela-mainchain/node_crc/mainchain-crc-3/keystore.dat:/ela/keystore.dat
    ports:
      - 10311-10317:20333-20339
    networks:
      - blockchain
    tty: true

  ela-mainchain-crc-4:
    container_name: ela-mainchain-crc-4
    image: cyberrepublic/elastos-mainchain-node:v0.3.2
    depends_on:
      - ela-mainchain-normal-1
    volumes:
      - ~/.volumes/elastos-privnet/mainchain-crc-4:/ela/elastos
      - ${PWD}/ela-mainchain/node_crc/mainchain-crc-4/config.json:/ela/config.json
      - ${PWD}/ela-mainchain/node_crc/mainchain-crc-4/keystore.dat:/ela/keystore.dat
    ports:
      - 10411-10417:20333-20339
    networks:
      - blockchain
    tty: true

  ela-mainchain-dpos-1:
    container_name: ela-mainchain-dpos-1
    image: cyberrepublic/elastos-mainchain-node:v0.3.2
    depends_on:
      - ela-mainchain-normal-1
    volumes:
      - ~/.volumes/elastos-privnet/mainchain-dpos-1:/ela/elastos
      - ${PWD}/ela-mainchain/node_dpos/mainchain-dpos-1/config.json:/ela/config.json
      - ${PWD}/ela-mainchain/node_dpos/mainchain-dpos-1/keystore.dat:/ela/keystore.dat
    ports:
      - 10511-10517:20333-20339
    networks:
      - blockchain
    tty: true

  ela-mainchain-dpos-2:
    container_name: ela-mainchain-dpos-2
    image: cyberrepublic/elastos-mainchain-node:v0.3.2
    depends_on:
      - ela-mainchain-normal-1
    volumes:
      - ~/.volumes/elastos-privnet/mainchain-dpos-2:/ela/elastos
      - ${PWD}/ela-mainchain/node_dpos/mainchain-dpos-2/config.json:/ela/config.json
      - ${PWD}/ela-mainchain/node_dpos/mainchain-dpos-2/keystore.dat:/ela/keystore.dat
    ports:
      - 10611-10617:20333-20339
    networks:
      - blockchain
    tty: true

  ela-arbitrator-crc-1:
    container_name: ela-arbitrator-crc-1
    image: cyberrepublic/elastos-arbitrator-node:v0.1.1
    depends_on:
      - ela-mainchain-crc-1
      - ela-sidechain-did-1
      - ela-sidechain-token-1
    volumes:
      - ~/.volumes/elastos-privnet/arbitrator-crc-1:/arbiter/elastos_arbiter
      - ${PWD}/ela-arbitrator/node_crc/arbitrator-crc-1/config.json:/arbiter/config.json
      - ${PWD}/ela-arbitrator/node_crc/arbitrator-crc-1/keystore.dat:/arbiter/keystore.dat
    ports:
      - 50114-50118:20534-20538
    networks:
      - blockchain
    tty: true

  ela-arbitrator-crc-2:
    container_name: ela-arbitrator-crc-2
    image: cyberrepublic/elastos-arbitrator-node:v0.1.1
    depends_on:
      - ela-mainchain-crc-2
      - ela-sidechain-did-2
      - ela-sidechain-token-2
    volumes:
      - ~/.volumes/elastos-privnet/arbitrator-crc-2:/arbiter/elastos_arbiter
      - ${PWD}/ela-arbitrator/node_crc/arbitrator-crc-2/config.json:/arbiter/config.json
      - ${PWD}/ela-arbitrator/node_crc/arbitrator-crc-2/keystore.dat:/arbiter/keystore.dat
    ports:
      - 50214-50218:20534-20538
    networks:
      - blockchain
    tty: true

  ela-arbitrator-crc-3:
    container_name: ela-arbitrator-crc-3
    image: cyberrepublic/elastos-arbitrator-node:v0.1.1
    depends_on:
      - ela-mainchain-crc-3
      - ela-sidechain-did-3
      - ela-sidechain-token-3
    volumes:
      - ~/.volumes/elastos-privnet/arbitrator-crc-3:/arbiter/elastos_arbiter
      - ${PWD}/ela-arbitrator/node_crc/arbitrator-crc-3/config.json:/arbiter/config.json
      - ${PWD}/ela-arbitrator/node_crc/arbitrator-crc-3/keystore.dat:/arbiter/keystore.dat
    ports:
      - 50314-50318:20534-20538
    networks:
      - blockchain
    tty: true

  ela-arbitrator-crc-4:
    container_name: ela-arbitrator-crc-4
    image: cyberrepublic/elastos-arbitrator-node:v0.1.1
    depends_on:
      - ela-mainchain-crc-4
      - ela-sidechain-did-4
      - ela-sidechain-token-4
    volumes:
      - ~/.volumes/elastos-privnet/arbitrator-crc-4:/arbiter/elastos_arbiter
      - ${PWD}/ela-arbitrator/node_crc/arbitrator-crc-4/config.json:/arbiter/config.json
      - ${PWD}/ela-arbitrator/node_crc/arbitrator-crc-4/keystore.dat:/arbiter/keystore.dat
    ports:
      - 50414-50418:20534-20538
    networks:
      - blockchain
    tty: true

  ela-arbitrator-origin-1:
    container_name: ela-arbitrator-origin-1
    image: cyberrepublic/elastos-arbitrator-node:v0.1.1
    depends_on:
      - ela-mainchain-dpos-1
      - ela-sidechain-did-1
      - ela-sidechain-token-1
    volumes:
      - ~/.volumes/elastos-privnet/arbitrator-origin-1:/arbiter/elastos_arbiter
      - ${PWD}/ela-arbitrator/node_origin/arbitrator-origin-1/config.json:/arbiter/config.json
      - ${PWD}/ela-arbitrator/node_origin/arbitrator-origin-1/keystore.dat:/arbiter/keystore.dat
    ports:
      - 50514-50518:20534-20538
    networks:
      - blockchain
    tty: true

  ela-arbitrator-origin-2:
    container_name: ela-arbitrator-origin-2
    image: cyberrepublic/elastos-arbitrator-node:v0.1.1
    depends_on:
      - ela-mainchain-dpos-2
      - ela-sidechain-did-2
      - ela-sidechain-token-2
    volumes:
      - ~/.volumes/elastos-privnet/arbitrator-origin-2:/arbiter/elastos_arbiter
      - ${PWD}/ela-arbitrator/node_origin/arbitrator-origin-2/config.json:/arbiter/config.json
      - ${PWD}/ela-arbitrator/node_origin/arbitrator-origin-2/keystore.dat:/arbiter/keystore.dat
    ports:
      - 50614-50618:20534-20538
    networks:
      - blockchain
    tty: true

  ela-sidechain-did-1:
    container_name: ela-sidechain-did-1
    image: cyberrepublic/elastos-sidechain-did-node:v0.1.2
    depends_on:
      - ela-mainchain-normal-1
      - ela-mainchain-dpos-1
      - ela-mainchain-crc-1
    volumes:
      - ~/.volumes/elastos-privnet/did-1:/did/elastos_did
      - ${PWD}/ela-sidechain/did/did-1/config.json:/did/config.json
    ports:
      - 30111-30115:20604-20608
    networks:
      - blockchain
    tty: true 

  ela-sidechain-did-2:
    container_name: ela-sidechain-did-2
    image: cyberrepublic/elastos-sidechain-did-node:v0.1.2
    depends_on:
      - ela-mainchain-normal-1
      - ela-mainchain-dpos-2
      - ela-mainchain-crc-2
    volumes:
      - ~/.volumes/elastos-privnet/did-2:/did/elastos_did
      - ${PWD}/ela-sidechain/did/did-2/config.json:/did/config.json
    ports:
      - 30211-30215:20604-20608
    networks:
      - blockchain
    tty: true 

  ela-sidechain-did-3:
    container_name: ela-sidechain-did-3
    image: cyberrepublic/elastos-sidechain-did-node:v0.1.2
    depends_on:
      - ela-mainchain-normal-1
      - ela-mainchain-crc-3
    volumes:
      - ~/.volumes/elastos-privnet/did-3:/did/elastos_did
      - ${PWD}/ela-sidechain/did/did-3/config.json:/did/config.json
    ports:
      - 30311-30315:20604-20608
    networks:
      - blockchain
    tty: true 

  ela-sidechain-did-4:
    container_name: ela-sidechain-did-4
    image: cyberrepublic/elastos-sidechain-did-node:v0.1.2
    depends_on:
      - ela-mainchain-normal-1
      - ela-mainchain-crc-4
    volumes:
      - ~/.volumes/elastos-privnet/did-4:/did/elastos_did
      - ${PWD}/ela-sidechain/did/did-4/config.json:/did/config.json
    ports:
      - 30411-30415:20604-20608
    networks:
      - blockchain
    tty: true 

  ela-sidechain-token-1:
    container_name: ela-sidechain-token-1
    image: cyberrepublic/elastos-sidechain-token-node:v0.1.2
    depends_on:
      - ela-mainchain-normal-1
      - ela-mainchain-dpos-1
      - ela-mainchain-crc-1
    volumes:
      - ~/.volumes/elastos-privnet/token-1:/token/elastos_token
      - ${PWD}/ela-sidechain/token/token-1/config.json:/token/config.json
    ports:
      - 40111-40115:20614-20618
    networks:
      - blockchain
    tty: true 

  ela-sidechain-token-2:
    container_name: ela-sidechain-token-2
    image: cyberrepublic/elastos-sidechain-token-node:v0.1.2
    depends_on:
      - ela-mainchain-normal-1
      - ela-mainchain-dpos-2
      - ela-mainchain-crc-2
    volumes:
      - ~/.volumes/elastos-privnet/token-2:/token/elastos_token
      - ${PWD}/ela-sidechain/token/token-2/config.json:/token/config.json
    ports:
      - 40211-40215:20614-20618
    networks:
      - blockchain
    tty: true 

  ela-sidechain-token-3:
    container_name: ela-sidechain-token-3
    image: cyberrepublic/elastos-sidechain-token-node:v0.1.2
    depends_on:
      - ela-mainchain-normal-1
      - ela-mainchain-crc-3
    volumes:
      - ~/.volumes/elastos-privnet/token-3:/token/elastos_token
      - ${PWD}/ela-sidechain/token/token-3/config.json:/token/config.json
    ports:
      - 40311-40315:20614-20618
    networks:
      - blockchain
    tty: true 

  ela-sidechain-token-4:
    container_name: ela-sidechain-token-4
    image: cyberrepublic/elastos-sidechain-token-node:v0.1.2
    depends_on:
      - ela-mainchain-normal-1
      - ela-mainchain-crc-4
    volumes:
      - ~/.volumes/elastos-privnet/token-4:/token/elastos_token
      - ${PWD}/ela-sidechain/token/token-4/config.json:/token/config.json
    ports:
      - 40411-40415:20614-20618
    networks:
      - blockchain
    tty: true 

  ela-wallet-service:
    container_name: ela-wallet-service
    image: cyberrepublic/elastos-wallet-service:latest
    depends_on:
      - ela-mainchain-normal-1
    ports:
      - 8091:8080
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8091/api/1/currHeight"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - blockchain
    tty: true 

  ela-did-service:
    container_name: ela-did-service
    image: cyberrepublic/elastos-did-service:latest
    depends_on:
      - ela-mainchain-normal-1
      - ela-sidechain-did-1
    ports:
      - 8092:8080
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8092/api/1/currHeight"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - blockchain
    tty: true 

  ela-api-misc-mainchain:
    container_name: ela-api-misc-mainchain
    image: cyberrepublic/elastos-api-misc-service:latest
    volumes:
      - ${PWD}/restful-services/api-misc/mainchain/config.json:/home/elauser/config.json
      - ${PWD}/restful-services/api-misc/mainchain/deploy.sh:/home/elauser/deploy.sh
    depends_on:
      - ela-mysql
      - ela-mainchain-normal-1
    ports:
      - 9091:8080
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9091/api/1/ping"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - blockchain
    tty: true

  ela-api-misc-sidechain-did:
    container_name: ela-api-misc-sidechain-did
    image: cyberrepublic/elastos-api-misc-service:latest
    volumes:
      - ${PWD}/restful-services/api-misc/sidechain/did/config.json:/home/elauser/config.json
      - ${PWD}/restful-services/api-misc/sidechain/did/deploy.sh:/home/elauser/deploy.sh
    depends_on:
      - ela-mysql
      - ela-sidechain-did-1
    ports:
      - 9092:8080
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9092/api/1/ping"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - blockchain
    tty: true

  ela-mysql:
    container_name: ela-mysql
    image: mysql:5.6
    volumes:
      - ~/.volumes/elastos-privnet/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=12345678
      - MYSQL_DATABASE=ws
      - MYSQL_USER=elastos
      - MYSQL_PASSWORD=12345678
    ports:
      - 3307:3306
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - blockchain
    tty: true

networks:
  blockchain:
